# Generated by Django 5.1.3 on 2024-12-20 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_equipo_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='en_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='app.trabajador'),
        ),
    ]
